### ISSUE TITLE
Cannot read/write SerialPort on non-ARM?

### ISSUE THREAD

**Issue by auscompgeek** [Lytigas/first-rust-competition#34]
#30 broke being able to read from/write to a SerialPort in simulation (assuming one could use this with the halsim libraries).

Not sure why #29 was closed.

**Comment by auscompgeek** [comment]
Also related: there would currently be no way to compile this crate for an architecture that isn't ARM or x86, even if one had a HAL for their target platform.

**Comment by Lytigas** [comment]
You are correct. I closed #29 because #30 had the same functionality + the Read/Write impls. The reason I wanted to keep the crate "compiling" on x86 is so that the RLS (I use vscode + RLS) doesn't error there all the time as I develop. I assumed others would have had similar problems.

Simulation seems a decent ways away, even for upstream WPILib, so I wasn't too worried about it. Re-examining it, though, casting is probably better.
